export const ARTICLE_STATUS = {
  EMPTY: 'EMPTY',
  WRITING: 'WRITING',
  WAITING: 'WAITING',
  PLANNING: 'PLANNING',
  PUBLISHED: 'PUBLISHED',
  DELETED: 'DELETED'
}

export const USER_STATUS = {
  REDACTOR: 'REDACTOR',
  WRITER: 'WRITER'
}
